# Generated by Django 5.1 on 2024-09-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatmug_assignment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='vendor_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
